SELECT CURRENT_ROLE();
SELECT CURRENT_USER();
SELECT CURRENT_ACCOUNT();
SELECT CURRENT_REGION();

-- 1. データベースを作成
CREATE DATABASE TRAINING_DB;

-- 2. スキーマを作成
CREATE SCHEMA TRAINING_DB.HANDS_ON;

-- 3. テーブルを作成
--    Snowflakeが内部で自動的に列指向・圧縮フォーマットに変換して保存する
CREATE TABLE TRAINING_DB.HANDS_ON.EMPLOYEES (
  ID        INTEGER,
  NAME      VARCHAR(100),
  DEPT      VARCHAR(50),
  HIRE_DATE DATE
);

-- 4. データを挿入
INSERT INTO TRAINING_DB.HANDS_ON.EMPLOYEES VALUES
  (1, 'Alice', 'Engineering', '2023-01-15'),
  (2, 'Bob',   'Sales',       '2023-03-20'),
  (3, 'Carol', 'Engineering', '2022-11-01');

-- 5. クエリ実行
SELECT * FROM TRAINING_DB.HANDS_ON.EMPLOYEES;

-- 6. 作成したオブジェクトを確認
SHOW DATABASES LIKE 'TRAINING%';
SHOW SCHEMAS IN DATABASE TRAINING_DB;
SHOW TABLES IN SCHEMA TRAINING_DB.HANDS_ON;



-- 1. ウェアハウスを作成（停止状態で作成される）
CREATE WAREHOUSE TRAINING_WH
  WAREHOUSE_SIZE    = 'X-SMALL'
  AUTO_SUSPEND      = 60        -- 60秒アイドルで自動停止
  AUTO_RESUME       = TRUE      -- クエリ実行時に自動起動
  INITIALLY_SUSPENDED = TRUE;   -- 作成時は停止状態

-- 2. ウェアハウスを使用してクエリを実行（自動でResumeされる）
USE WAREHOUSE TRAINING_WH;
SELECT COUNT(*) FROM TRAINING_DB.HANDS_ON.EMPLOYEES;

-- 3. ウェアハウスの状態・サイズ・クレジット使用状況を確認
SHOW WAREHOUSES;

-- 4. 手動でサスペンド
ALTER WAREHOUSE TRAINING_WH SUSPEND;

-- 5. クレジット使用履歴を確認（ACCOUNTADMIN権限が必要）
SELECT *
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE WAREHOUSE_NAME = 'TRAINING_WH'
ORDER BY START_TIME DESC
LIMIT 10;