/*
WAREHOUSEの稼働(RESUME)/停止(SUSPEND)を確認するため、キャッシュの利用を無効化する。
クエリ実行時にキャッシュを利用している場合はWHを利用しない。
*/
ALTER SESSION SET USE_CACHED_RESULT = FALSE;

-- HANDSON①
SELECT CURRENT_ROLE();
SELECT CURRENT_USER();
SELECT CURRENT_ACCOUNT();
SELECT CURRENT_REGION();


-- HANDSON②
USE ROLE ACCOUNTADMIN;

-- 1. データベースを作成
CREATE OR REPLACE DATABASE N01_SETUP;

-- 2. スキーマを作成
CREATE OR REPLACE SCHEMA N01_SETUP.HANDS_ON;

-- 3. テーブルを作成
--    Snowflakeが内部で自動的に列指向・圧縮フォーマットに変換して保存する
CREATE OR REPLACE TABLE N01_SETUP.HANDS_ON.EMPLOYEES (
  ID        INTEGER,
  NAME      VARCHAR(100),
  DEPT      VARCHAR(50),
  HIRE_DATE DATE
);

-- 4. データを挿入
INSERT INTO N01_SETUP.HANDS_ON.EMPLOYEES VALUES
  (1, 'Alice', 'Engineering', '2023-01-15'),
  (2, 'Bob',   'Sales',       '2023-03-20'),
  (3, 'Carol', 'Engineering', '2022-11-01');

-- 5. クエリ実行
SELECT * FROM N01_SETUP.HANDS_ON.EMPLOYEES;

-- 6. 作成したオブジェクトを確認
SHOW DATABASES LIKE 'N01_SETUP%';
SHOW SCHEMAS IN DATABASE N01_SETUP;
SHOW TABLES IN SCHEMA N01_SETUP.HANDS_ON;


-- HANDSON③
-- 1. ウェアハウスを作成（停止状態で作成される）
CREATE OR REPLACE WAREHOUSE N01_WH
  WAREHOUSE_SIZE    = 'X-SMALL'
  AUTO_SUSPEND      = 60        -- 60秒アイドルで自動停止
  AUTO_RESUME       = FALSE      -- クエリ実行時に自動で起動しない。
  INITIALLY_SUSPENDED = TRUE;   -- 作成時は停止状態

SHOW WAREHOUSES;

-- 2. ウェアハウスを使用してクエリを実行
USE WAREHOUSE N01_WH;
SELECT * FROM N01_SETUP.HANDS_ON.EMPLOYEES; -- WHがSUSPEND状態のため失敗する。

ALTER WAREHOUSE N01_WH RESUME; -- WHを起動する。
SELECT * FROM N01_SETUP.HANDS_ON.EMPLOYEES; -- WHがRESUME状態になったため成功する。

-- 3. ウェアハウスの状態・サイズ・クレジット使用状況を確認
SHOW WAREHOUSES;

-- 4. 手動でサスペンド
ALTER WAREHOUSE N01_WH SUSPEND;
SHOW WAREHOUSES;

-- 5. クレジット使用履歴を確認（ACCOUNTADMIN権限が必要）
USE WAREHOUSE COMPUTE_WH;
SELECT *
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE WAREHOUSE_NAME = 'N01_WH'
ORDER BY START_TIME DESC
LIMIT 10;