-- HANDSON①
-- 0. 環境セットアップ（DB・スキーマ・ウェアハウスを作成）
USE ROLE SYSADMIN;

CREATE OR REPLACE DATABASE N04;
CREATE OR REPLACE SCHEMA N04.HANDS_ON;
CREATE OR REPLACE WAREHOUSE N04_WH
  WAREHOUSE_SIZE      = 'X-SMALL'
  AUTO_SUSPEND        = 60      -- 60秒アイドルで自動停止
  AUTO_RESUME         = TRUE    -- クエリ実行時に自動起動
  INITIALLY_SUSPENDED = TRUE;   -- 作成時は停止状態

USE DATABASE N04;
USE SCHEMA N04.HANDS_ON;
USE WAREHOUSE N04_WH;

-- 1. サンプルテーブル作成
CREATE OR REPLACE TABLE ORDERS (
  ORDER_ID INTEGER,
  CUSTOMER VARCHAR(100),
  AMOUNT   NUMBER(10,2)
) DATA_RETENTION_TIME_IN_DAYS = 1;

INSERT INTO ORDERS VALUES (1, 'Alice', 1000), (2, 'Bob', 2000), (3, 'Carol', 3000);

-- 2. 現在時刻を記録（Time Travel用）
SELECT CURRENT_TIMESTAMP;  -- この時刻をメモしておく

-- 3. 誤ってデータを削除
DELETE FROM ORDERS WHERE CUSTOMER = 'Alice';
SELECT * FROM ORDERS;  -- Aliceが消えた！

-- 4. Time Travel で削除前のデータを参照する。
SELECT * FROM ORDERS AT(OFFSET => -60);  -- 60秒前のデータ
-- または
SELECT QUERY_ID, QUERY_TEXT, DATABASE_NAME, SCHEMA_NAME, QUERY_TYPE, START_TIME
FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY())
WHERE DATABASE_NAME = 'N04' AND QUERY_TYPE = 'DELETE'
ORDER BY start_time;
SELECT * FROM ORDERS BEFORE(STATEMENT => '<query_id>');

-- 5.データを復元する
CREATE OR REPLACE TABLE ORDERS_RESTORED AS
    SELECT * FROM ORDERS BEFORE(STATEMENT => '<query_id>');
ALTER TABLE ORDERS SWAP WITH ORDERS_RESTORED; -- 中身を入れ替え
DROP TABLE ORDERS_RESTORED; -- 後片付け
SELECT * FROM ORDERS; -- 確認

-- 5. 誤って DROP したテーブルを復元
DROP TABLE ORDERS;
UNDROP TABLE ORDERS;  -- 復元！
SELECT * FROM ORDERS;

-- 6. 保持期間(retention_time)の確認
SHOW TABLES LIKE 'ORDERS';


-- HANDSON②
-- 1. テーブルのクローンを作成（コストゼロ・一瞬で完了）
CREATE OR REPLACE TABLE ORDERS_CLONE CLONE ORDERS;

-- 2. クローンは独立している → 元テーブルの変更は反映されない(ストレージコストとしては、お互いの差分おみが追加課金となる。)
INSERT INTO ORDERS VALUES (4, 'David', 4000);
SELECT * FROM ORDERS;        -- 4行
SELECT * FROM ORDERS_CLONE;  -- 3行（Davidは入っていない）

-- 3. クローンに変更を加えても元テーブルに影響なし
DELETE FROM ORDERS_CLONE WHERE CUSTOMER = 'Bob';
SELECT * FROM ORDERS;        -- Bobは残っている
SELECT * FROM ORDERS_CLONE;  -- Bobが消えた

-- 4. 過去時点のクローンを作成
CREATE TABLE ORDERS_BEFORE CLONE ORDERS
  AT(OFFSET => -120);  -- 2分前の状態からクローン

-- 5. スキーマ全体もクローン可
CREATE SCHEMA HANDS_ON_BACKUP CLONE HANDS_ON;


-- HANDSON③
-- 1. 共有操作は ACCOUNTADMIN で実施し、コンテキストも明示する
--    （ビューが N04.HANDS_ON 以外に作られると、後続の GRANT が
--      "does not exist or not authorized" になるため）
USE ROLE ACCOUNTADMIN;
USE DATABASE N04;
USE SCHEMA N04.HANDS_ON;
USE WAREHOUSE N04_WH;

-- 2. 共有するビューをセキュアビューとして作成
CREATE OR REPLACE SECURE VIEW ORDERS_SECURE_VIEW AS
  SELECT ORDER_ID, CUSTOMER, AMOUNT FROM ORDERS;

-- 3. シェアを作成（再実行に備えて OR REPLACE）
CREATE OR REPLACE SHARE TRAINING_SHARE
  COMMENT = '学習用データ共有';

-- 4. シェアに権限を付与
GRANT USAGE ON DATABASE N04 TO SHARE TRAINING_SHARE;
GRANT USAGE ON SCHEMA N04.HANDS_ON TO SHARE TRAINING_SHARE;
GRANT SELECT ON VIEW N04.HANDS_ON.ORDERS_SECURE_VIEW TO SHARE TRAINING_SHARE;

-- 1. 共有操作は ACCOUNTADMIN で実施し、コンテキストも明示する
--    （ビューが N04.HANDS_ON 以外に作られると、後続の GRANT が
--      "does not exist or not authorized" になるため）
USE ROLE ACCOUNTADMIN;
USE DATABASE N04;
USE SCHEMA N04.HANDS_ON;
USE WAREHOUSE N04_WH;

-- 2. 共有するビューをセキュアビューとして作成
CREATE OR REPLACE SECURE VIEW ORDERS_SECURE_VIEW AS
  SELECT ORDER_ID, CUSTOMER, AMOUNT FROM ORDERS;

-- 3. シェアを作成（再実行に備えて OR REPLACE）
CREATE OR REPLACE SHARE TRAINING_SHARE
  COMMENT = '学習用データ共有';

-- 4. シェアに権限を付与
GRANT USAGE ON DATABASE N04 TO SHARE TRAINING_SHARE;
GRANT USAGE ON SCHEMA N04.HANDS_ON TO SHARE TRAINING_SHARE;
GRANT SELECT ON VIEW N04.HANDS_ON.ORDERS_SECURE_VIEW TO SHARE TRAINING_SHARE;

-- 5. Consumer アカウントをシェアに追加（同リージョン・同クラウドのアカウント）
-- ALTER SHARE TRAINING_SHARE ADD ACCOUNTS = <組織名>.<アカウント名>; -- 例: HMQBYRX.LZ73219
-- エディション差で弾かれる場合の例
-- ALTER SHARE TRAINING_SHARE ADD ACCOUNTS = <組織名>.<アカウント名> SHARE_RESTRICTIONS = FALSE;

-- 6. シェアの内容を確認
SHOW SHARES;
DESCRIBE SHARE TRAINING_SHARE;

-- 7. データ保持期間の設定確認
SHOW PARAMETERS LIKE 'DATA_RETENTION%' IN ACCOUNT;


/*
▼ Consumer アカウント側で実行 ▼
USE ROLE ACCOUNTADMIN;

-- 1. 受信した共有を確認（INBOUND に TRAINING_SHARE が見える）
SHOW SHARES;
DESC SHARE <provider組織名>.<providerアカウント名>.TRAINING_SHARE;

-- 2. 共有からデータベースを作成（読み取り専用でマウント）
CREATE DATABASE SHARED_TRAINING
  FROM SHARE <provider組織名>.<providerアカウント名>.TRAINING_SHARE;

-- 3. ACCOUNTADMIN以外のロールにも使わせる場合は権限を移譲
GRANT IMPORTED PRIVILEGES ON DATABASE SHARED_TRAINING TO ROLE SYSADMIN;

-- 4. 参照（SELECTのみ可能）
SELECT * FROM SHARED_TRAINING.HANDS_ON.ORDERS_SECURE_VIEW;
*/